version: '3.6'

networks :
   drianet:

services:
 go:
   image: "go:latest"
   build: .
   ports: 
     - '8000:8000'
   networks: 
     - 'drianet'

 postgres:
   image: "postgres:latest"
   environment:
     - 'POSTGRES_PASSWORD=123456789'
   networks: 
     - 'drianet'
