version: '3.6'

services:
 go:
   image: "go:latest"
   ports: 
     - '8000:8000'

 postgres:
   image: "postgres:latest"
   ports: 
     - "0000:0000"
   environment:
     - POSTGRES_PASSWORD=123456789
